name: Publish SNAPSHOT to GitHub Packages

on:
  push:
    branches:
      - main  # deploy on each commit to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>h2a26</username>
                <password>${{ secrets.PAT_CLASSIC }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and Deploy SNAPSHOT
        run: mvn clean deploy -DskipTests
